//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by mswin.rc
//
#define IDC_ERROR_CLEAR                 3
#define IDC_ERROR_MARK                  3
#define IDC_ERROR_REFRESH               4
#define IDC_ERROR_CHECK                 5
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDS_PRODUCT                     129
#define IDD_FINDREPL                    203
#define IDR_POPUP                       204
#define IDD_PROJECT_PROPERTIES          210
#define IDD_FILE_PROPERTIES             215
#define IDD_GENERATE                    307
#define IDD_MIXER_SETUP                 309
#define IDD_WT_SELECT                   311
#define IDD_GET_VALUE                   312
#define IDD_INSTR_PROPERTIES            313
#define IDD_KEYBOARD                    314
#define IDD_EFFECTS                     320
#define IDD_LIB_PROPERTIES              321
#define IDD_SELECT_INSTR                323
#define IDD_OPTIONS                     324
#define IDD_WVF_PROPERTIES              325
#define IDD_NAME_PROPERTIES             326
#define IDD_SCORE_ERRORS                349
#define IDB_CCLIC                       350
#define IDD_MODSYNTH_CONFIG             351
#define IDD_MODSYNTH_CONNECT            352
#define IDD_FILE_ORDER                  353
#define IDD_SOUNDBANK_SEL               355
#define IDD_SOUNDBANK_PROPERTIES        356
#define IDB_Add16                       400
#define IDB_Add32                       401
#define IDB_AddItem16                   402
#define IDB_AddItem32                   403
#define IDB_All16                       404
#define IDB_All32                       405
#define IDB_CD16                        406
#define IDB_CD32                        407
#define IDB_CloseItem16                 408
#define IDB_CloseItem32                 409
#define IDB_Copy16                      410
#define IDB_Copy32                      411
#define IDB_CopyItem16                  412
#define IDB_CopyItem32                  413
#define IDB_Cut16                       414
#define IDB_Cut32                       415
#define IDB_DeleteItem16                416
#define IDB_DeleteItem32                417
#define IDB_Down16                      418
#define IDB_Down32                      419
#define IDB_EditItem16                  420
#define IDB_EditItem32                  421
#define IDB_Find32                      422
#define IDB_FindNext16                  423
#define IDB_FindNext16_1                424
#define IDB_FindNext32                  425
#define IDB_FindNext32_1                426
#define IDB_Help16                      427
#define IDB_Help32                      428
#define IDB_Info16                      429
#define IDB_Info32                      430
#define IDB_Item16                      431
#define IDB_Item32                      432
#define IDB_ItemHelp16                  433
#define IDB_ItemHelp32                  434
#define IDB_ItemProperties16            435
#define IDB_ItemProperties32            436
#define IDB_Keyboard16                  437
#define IDB_Keyboard16_1                438
#define IDB_Keyboard32                  439
#define IDB_NewItem16                   440
#define IDB_NewItem32                   441
#define IDB_NewProject16                442
#define IDB_NewProject16_1              443
#define IDB_NewProject32                444
#define IDB_NewProject32_1              445
#define IDB_OpenProject16               446
#define IDB_OpenProject16_1             447
#define IDB_OpenProject32               448
#define IDB_OpenProject32_1             449
#define IDB_Part16                      450
#define IDB_Part32                      451
#define IDB_Paste16                     452
#define IDB_Paste32                     453
#define IDB_Pause32                     454
#define IDB_ProjectProperties16         455
#define IDB_ProjectProperties32         456
#define IDB_Redo32                      457
#define IDB_Remove16                    458
#define IDB_Remove32                    459
#define IDB_Save16                      460
#define IDB_Save32                      461
#define IDB_SaveAll16                   462
#define IDB_SaveAll32                   463
#define IDB_SaveAs16                    464
#define IDB_SaveAs32                    465
#define IDB_SaveProject16               466
#define IDB_SaveProject32               467
#define IDB_SaveProjectAs16             468
#define IDB_SaveProjectAs32             469
#define IDB_Speaker16                   470
#define IDB_Speaker32                   471
#define IDB_Start32                     472
#define IDB_Stop32                      473
#define IDB_Undo32                      474
#define IDB_Up16                        475
#define IDB_Up32                        476
#define IDI_START                       476
#define IDB_Undo16                      477
#define IDI_STOP                        477
#define IDB_Redo16                      478
#define IDI_PAUSE                       478
#define IDB_Find16                      479
#define IDI_SPEAKER                     479
#define IDI_CD                          480
#define IDI_PART                        481
#define IDI_ALL                         482
#define IDI_MVUP                        483
#define IDI_MVDN                        484
#define IDI_ADD                         485
#define IDI_REM                         486
#define IDB_Up32_1                      487
#define IDB_Down32_1                    488
#define IDB_AddItem_1                   489
#define IDB_AddItem_2                   490
#define IDB_DeleteItem16_1              491
#define IDB_DeleteItem32_1              492
#define IDB_DeleteItem16_2              493
#define IDB_DeleteItem32_2              494
#define IDB_AddItem16_1                 495
#define IDB_AddItem32_1                 496
#define IDB_AddItem16_2                 497
#define IDB_AddItem32_2                 498
#define IDB_Up16_1                      499
#define IDB_Down16_1                    500
#define IDI_ICON1                       501
#define IDI_INFO                        501
#define IDB_Help16_1                    502
#define IDB_Info16_1                    503
#define IDB_Help32_1                    504
#define IDB_Info32_1                    505
#define IDB_Pause32_1                   506
#define IDB_Start32_1                   507
#define IDB_Stop32_1                    508
#define IDB_Start32_2                   509
#define IDB_Stop32_2                    510
#define IDB_BITMAP1                     512
#define IDB_Pause32_2                   512
#define IDB_BITMAP2                     513
#define IDC_FIND_TEXT                   1000
#define IDC_REPL_TEXT                   1001
#define IDC_MATCH_CASE                  1002
#define IDC_WHOLE_WORD                  1003
#define IDC_REGEXP                      1004
#define IDC_START_WORD                  1005
#define IDC_FIND_NEXT                   1006
#define IDC_REPLACE                     1007
#define IDC_REPLACE_ALL                 1008
#define IDC_STAT_TEXT                   1009
#define IDC_PROJECT_FILE                1010
#define IDC_REPLACE_SELALL              1010
#define IDC_PROJECT_NAME                1011
#define IDC_PROJECT_DESCR               1012
#define IDC_PROJECT_COMPOSER            1013
#define IDC_PROJECT_OUTPUT              1014
#define IDC_PROJECT_OUT_BROWSE          1015
#define IDC_PROJECT_WV_BROWSE           1016
#define IDC_PROJECT_SAMPLERATE          1022
#define IDC_PROJECT_WTSIZE              1023
#define IDC_PROJECT_WTUSER              1026
#define IDC_PROJECT_SAMPLEFMT           1027
#define IDC_PROJECT_COPYRIGHT           1028
#define IDC_PROJECT_PATH                1029
#define IDC_PROJECT_PATH_ADD            1033
#define IDC_PROJECT_PATH_REM            1034
#define IDC_PROJECT_PATH_UP             1035
#define IDC_FILE_NAME                   1035
#define IDC_PROJECT_PATH_DN             1036
#define IDC_PROJECT_IN_BROWSE           1037
#define IDC_FILE_INCLUDE                1039
#define IDC_FILE_BROWSE                 1040
#define IDC_START                       1041
#define IDC_TEXT                        1042
#define IDC_PLAY_ALL                    1043
#define IDC_PLAY_SOME                   1044
#define IDC_PLAY_FROM                   1045
#define IDC_PLAY_TO                     1046
#define IDC_TIME                        1047
#define IDC_STOP                        1048
#define IDC_PAUSE                       1049
#define IDC_WV_NAME                     1050
#define IDC_LEFT_PEAK                   1050
#define IDC_WV_DESCR                    1051
#define IDC_RIGHT_PEAK                  1051
#define IDC_WV_GIBBS                    1053
#define IDC_WV_P1                       1054
#define IDC_WV_P2                       1055
#define IDC_WV_P3                       1056
#define IDC_WV_P4                       1057
#define IDC_WV_P5                       1058
#define IDC_WV_P6                       1059
#define IDC_WV_P7                       1060
#define IDC_WV_P8                       1061
#define IDC_WV_P9                       1062
#define IDC_WV_P10                      1063
#define IDC_WV_P11                      1064
#define IDC_WV_P12                      1065
#define IDC_WV_P13                      1066
#define IDC_WV_P14                      1067
#define IDC_WV_P15                      1068
#define IDC_WV_P16                      1069
#define IDC_WV_E1                       1070
#define IDC_WV_E2                       1071
#define IDC_WV_E3                       1072
#define IDC_WV_E4                       1073
#define IDC_WV_E5                       1074
#define IDC_WV_E6                       1075
#define IDC_WV_E7                       1076
#define IDC_WV_E8                       1077
#define IDC_WV_E9                       1078
#define IDC_WV_E10                      1079
#define IDC_WV_E11                      1080
#define IDC_WV_E12                      1081
#define IDC_WV_E13                      1082
#define IDC_WV_E14                      1083
#define IDC_WV_E15                      1084
#define IDC_WV_E16                      1085
#define IDC_WV_PH1                      1086
#define IDC_WV_PH2                      1087
#define IDC_WV_PH3                      1088
#define IDC_WV_PH4                      1089
#define IDC_WV_PH5                      1090
#define IDC_WV_PH6                      1091
#define IDC_WV_PH7                      1092
#define IDC_WV_PH8                      1093
#define IDC_WV_PH9                      1094
#define IDC_WV_PH10                     1095
#define IDC_WV_PH11                     1096
#define IDC_WV_PH12                     1097
#define IDC_WV_PH13                     1098
#define IDC_WV_PH14                     1099
#define IDC_WV_PH15                     1100
#define IDC_WV_PH16                     1101
#define IDC_WV_GRAPH                    1102
#define IDC_WV_REF                      1103
#define IDC_WV_M1                       1104
#define IDC_WV_M2                       1105
#define IDC_PLAY_LIVE                   1105
#define IDC_WV_M3                       1106
#define IDC_INPUTS                      1106
#define IDC_WV_M4                       1107
#define IDC_WV_M5                       1108
#define IDC_FX_TYPE                     1108
#define IDC_WV_M6                       1109
#define IDC_FX_LIST                     1109
#define IDC_WV_M7                       1110
#define IDC_PAN_LIN                     1110
#define IDC_WV_M8                       1111
#define IDC_PAN_TRIG                    1111
#define IDC_WV_M9                       1112
#define IDC_PAN_SQRT                    1112
#define IDC_WV_M10                      1113
#define IDC_FX_ADD                      1113
#define IDC_WV_M11                      1114
#define IDC_FX_REM                      1114
#define IDC_WV_M12                      1115
#define IDC_FX_UP                       1115
#define IDC_WV_M13                      1116
#define IDC_FX_DN                       1116
#define IDC_WV_M14                      1117
#define IDC_FX_EDIT                     1117
#define IDC_WV_M15                      1118
#define IDC_WT_LIST                     1118
#define IDC_WV_M16                      1119
#define IDC_WT_GRAPH                    1119
#define IDC_WV_CLR                      1120
#define IDC_VALUE                       1120
#define IDC_WV_SQR                      1121
#define IDC_PROMPT                      1121
#define IDC_WV_SAW                      1122
#define IDC_INST_TYPE                   1122
#define IDC_WV_SIN                      1124
#define IDC_WV_PLS                      1125
#define IDC_INST_NUM                    1125
#define IDC_INSTRUMENT                  1126
#define IDC_VOLUME                      1128
#define IDC_NOTE_W                      1130
#define IDC_NOTE_H                      1131
#define IDC_NOTE_Q                      1132
#define IDC_NOTE_E                      1133
#define IDC_NOTE_S                      1134
#define IDC_CHANNEL                     1136
#define IDC_RECORD                      1137
#define IDC_COPYNOTES                   1138
#define IDC_PROJECT_LEAD                1139
#define IDC_GROUP                       1139
#define IDC_PROJECT_TAIL                1140
#define IDC_FX_NAME                     1142
#define IDC_VAL1                        1143
#define IDC_VAL2                        1144
#define IDC_VAL3                        1145
#define IDC_VAL4                        1146
#define IDC_VAL5                        1147
#define IDC_EDIT1                       1148
#define IDC_EDIT2                       1149
#define IDC_EDIT3                       1150
#define IDC_EDIT4                       1151
#define IDC_EDIT5                       1152
#define IDC_RESET                       1153
#define IDC_PAN_LBL                     1154
#define IDC_PAN                         1155
#define IDC_VOL_LBL                     1156
#define IDC_VOL                         1157
#define IDC_PROJECT_WVPATH              1158
#define IDC_NAME_LBL                    1158
#define IDC_NAME_LBL2                   1160
#define IDC_INST_LIST                   1162
#define IDC_INCL_NOTELIST               1163
#define IDC_INCL_SEQUENCE               1164
#define IDC_INCL_SCRIPTS                1165
#define IDC_INCL_TEXTFILES              1166
#define IDC_DEF_PROJECTS                1167
#define IDC_DEF_AUTHOR                  1168
#define IDC_DEF_WAVEIN                  1169
#define IDC_DEF_FORMS                   1170
#define IDC_LATENCY                     1171
#define IDC_BROWSE_PROJECTS             1172
#define IDC_BROWSE_WAVEIN               1173
#define IDC_WV_TYPE                     1173
#define IDC_WV_PHSLBL                   1174
#define IDC_BROWSE_FORMS                1174
#define IDC_DEF_COPYRIGHT               1175
#define IDC_DEF_LIBRARIES               1176
#define IDC_WVF_ID                      1177
#define IDC_BROWSE_LIBRARIES            1177
#define IDC_INCL_LIBRARIES              1178
#define IDC_DEF_COLORS                  1179
#define IDC_SELTEXT                     1180
#define IDC_BROWSE_COLORS               1180
#define IDC_ALLTEXT                     1181
#define IDC_INCL_SOUNDFONTS             1181
#define IDC_INCL_SOUNDFONTS2            1182
#define IDC_INCL_MIDI                   1182
#define IDC_ITEM_NAME                   1184
#define IDC_ITEM_DESCR                  1185
#define IDC_GENERATE                    1187
#define IDC_SPEAKER                     1188
#define IDC_DISK                        1189
#define IDC_USE_SHARPS                  1190
#define IDC_USE_FLATS                   1191
#define IDC_KBD_LEFT                    1195
#define IDC_KBD_RIGHT                   1196
#define IDC_RENUMBER                    1199
#define IDC_ERROR_LIST                  1200
#define IDC_ERROR_ITEMS                 1201
#define IDC_ERROR_GOTO                  1202
#define IDC_ERROR_NEXT                  1203
#define IDC_ERROR_PREV                  1204
#define IDC_MS_TYPE                     1205
#define IDC_MS_UGENS                    1206
#define IDC_MS_ADD                      1207
#define IDC_MS_REM                      1208
#define IDC_MS_MVUP                     1209
#define IDC_MS_MVDN                     1210
#define IDC_MS_NAME                     1211
#define IDC_MC_SRC                      1212
#define IDC_MC_DST                      1213
#define IDC_MC_PARAM                    1214
#define IDC_MC_CONN                     1215
#define IDC_MC_ADD                      1216
#define IDC_MC_REM                      1217
#define IDC_FILE_LIST                   1218
#define IDC_FILE_UP                     1219
#define IDC_FILE_DN                     1220
#define IDC_MIDI_IN                     1222
#define IDC_WAVE_OUT                    1223
#define IDC_SB_FILE                     1224
#define IDC_SB_BANK                     1225
#define IDC_SB_PRESET                   1226
#define IDC_SB_PRELOAD                  1229
#define IDC_SB_SCALE                    1230
#define IDC_TIME_PROGRESS               1233
#define IDC_LPK_METER                   1234
#define IDC_RPK_METER                   1235
#define IDC_PEAK_ON                     1236
#define IDC_TIME_ON                     1237
#define IDC_RATE                        1242
#define ID_WINDOW_CLOSE                 32772
#define ID_WINDOW_CLOSE_ALL             32773
#define ID_VIEW_PROJECT                 32775
#define ID_VIEW_PLAYER                  32776
#define ID_VIEW_MIXER                   32777
#define ID_EDIT_PROPERTIES              32788
#define ID_EDIT_SELECTALL               32789
#define ID_EDIT_FINDREPLACE             32791
#define ID_PROJECT_GENERATE             32798
#define ID_PROJECT_PROPERTIES           32816
#define ID_PROJECT_PLAY                 32826
#define ID_NEW_PROJECT                  32829
#define ID_NEW_NOTELIST                 32830
#define ID_GEN_SOUND                    32854
#define ID_GEN_CD                       32855
#define ID_EDIT_FINDNEXT                32856
#define ID_EDIT_GOTOLINE                32857
#define ID_VIEW_KEYBOARD                32878
#define ID_PROJECT_OPTIONS              32899
#define ID_WINDOW_SAVE                  32905
#define ID_TABMENU_CLOSE                32913
#define ID_PROJECT_SAVE                 32923
#define ID_PROJECT_OPEN                 32924
#define ID_PROJECT_NEW                  32925
#define ID_ITEM_SAVE                    32926
#define ID_ITEM_SAVEAS                  32927
#define ID_ITEM_CLOSE                   32928
#define ID_ITEM_NEW                     32929
#define ID_ITEM_ADD                     32930
#define ID_ITEM_PROPERTIES              32931
#define ID_ITEM_EDIT                    32933
#define ID_ITEM_REMOVE                  32934
#define ID_PROJECT_SAVEAS               32937
#define ID_ITEM_COPY                    32938
#define ID_PROJECTITEMS_NEW             32944
#define ID_PROJECTITEMS_COPY            32945
#define ID_SYNTH_NEWWAVETABLE           32946
#define ID_SYNTH_PROPERTIES             32947
#define ID_WAVEOUT_PROPERTIES           32948
#define ID_FILELIST_NEWFILE             32949
#define ID_FILELIST_ADDEXISTINGFILE     32950
#define ID_Menu32951                    32951
#define ID_RECENTPROJECTS_FILE5         32952
#define ID_RECENTPROJECTS_FILE6         32953
#define ID_EDIT_PROPERTIES32954         32954
#define ID_EDIT_INFO                    32955
#define ID_ITEM_INFO                    32956
#define ID_PROJECTITEMS_INFO            32957
#define ID_ITEM_ERRORS                  32958
#define ID_VIEW_SCOREERRORS             32959
#define ID_HELP_CONTENTS                32968
#define ID_MARKER_SET                   32969
#define ID_MARKER_NEXT                  32970
#define ID_EDIT_SETMARKER               32973
#define ID_EDIT_NEXTMARKER              32974
#define ID_MARKER_PREV                  32975
#define ID_EDIT_PREVIOUSMARKER          32976
#define ID_EDIT_REMOVEALLMARKERS        32977
#define ID_MARKER_CLEAR                 32979
#define ID_Menu                         32980
#define ID_Menu32981                    32981
#define ID_FILELIST_PROPERTIES          32982
#define ID_LIBITEMS_ADDTOLIBRARY        32983
#define ID_LIBITEMS_COPYTOPROJECT       32984
#define ID_LIBITEMS_PROPERTIES          32985
#define ID_LIBITEMS_SAVELIBRARY         32986
#define ID_LIBITEMS_REMOVE              32987
#define ID_REMOVE_ITEM                  32988
#define ID_PROJECTITEMS_CHECK           32989
#define ID_ITEM_CHECK                   32990
#define ID_EDIT_CHECK                   32991

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        514
#define _APS_NEXT_COMMAND_VALUE         32992
#define _APS_NEXT_CONTROL_VALUE         1243
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
